# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [9]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [10]:
A = np.arange(1, 16).reshape(3,5)

In [11]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [12]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [13]:
print(B-C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [14]:
print(B*C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [15]:
print(B@C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [16]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(np.exp(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [35]:
print(np.min(B))

1


In [36]:
print(np.min(B, axis=0))

[1 2 3]


In [37]:
print(np.min(B, axis=1))

[1 4 7]


In [38]:
print(np.argmin(B))

0


In [39]:
print(np.argmin(B, axis = 0))

[0 0 0]


In [40]:
print(np.sum(B))

45


In [45]:
print(np.mean(B, axis=1))

[2. 5. 8.]


In [46]:
print(np.median(B, axis=1))

[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [33]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [144]:
A[1]

array([-3,  5,  1])

**Answer:**

Accessing A[1, 2] means we are providing two indices, one for the row (index 1) and one for the column (index 2). In this case we provide indices for both axes. A[1, 2] results a single element.

A[1] refers to the whole second row. The missing indices are considered complete slices. 
A[1] is the same as A[1, :] or A[1, ...].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [51]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


We can use the flat attribute which is an iterator over all the elements of the array.

In [57]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [41]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


The provided code creates an one-dimensional array 'a' that contains 30 elements from 0 to 29.
It then reshapes this one-dimensional array into a 3-dimensional array 'b' with the shape (2, 3, -1).
It organizes the data from the original 1D array 'a' into a 3D structure, where we can access elements using three indices.

The first dimension (2) specifies that the array has 2 "layers" or "slices." 
The second dimension (3) indicates that within each of the 2 layers, there are 3 rows. Each layer is a 2D array with 3 rows.
The third dimension (-1): 
When we use -1 for one of the dimensions while reshaping an array, it's a special way to instruct NumPy to automatically calculate the size of that dimension based on the total number of elements in the original array. NumPy will calculate the appropriate size for the specified dimension to ensure that the total number of elements remains the same.

In this case, it calculates the size of the third dimension to be 5 because 2 * 3 * 5 equals the total number of elements in the original 1D array.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [58]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1+m2)

[[2 3]
 [4 5]]


In [59]:
print(m1.shape)
print(m2.shape)

(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [46]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [48]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [68]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [72]:
def add_mult_matrices(matrix1, matrix2, add_or_multiply):

    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise ValueError("Both inputs should be of type numpy.ndarray")

    if add_or_multiply == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same size for addition")
        result = matrix1 + matrix2
    elif add_or_multiply == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix")
        result = np.dot(matrix1, matrix2)
    else:
        raise ValueError("Invalid operation. Use 'add' or 'multiply'")

    return result

In [78]:
print(add_mult_matrices(B, -2*A, 'add'))

[[ 0 -4  3]
 [ 0 -2 -4]]


In [79]:
print(add_mult_matrices(3*C, -E, 'add'))

ValueError: Matrices must have the same size for addition

In [75]:
print(add_mult_matrices(A, C, 'multiply'))

ValueError: Number of columns in the first matrix must be equal to the number of rows in the second matrix

In [76]:
print(add_mult_matrices(C, D, 'multiply'))

[[11 10]
 [10 11]]


In [77]:
print(add_mult_matrices(C, B, 'multiply'))

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [80]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [87]:
AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

print('AB:')
print(AB)
print('AC:')
print(AC)
    
if np.array_equal(AB, AC):
    print('AB = AC')
else: 
    print ('AB ̸= AC')
    
if not np.array_equal(B, C):
    print('B ≠ C')
else: 
    print('B = C')

AB:
[[ 4  7]
 [ 8 14]]
AC:
[[ 4  7]
 [ 8 14]]
AB = AC
B ≠ C


**Chap2. Question 3**

In [95]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

AD = add_mult_matrices(A, D, 'multiply')
DA = add_mult_matrices(D, A, 'multiply')

print('AD:', '\n', AD)
print('DA:', '\n', DA)


AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA: 
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [94]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

AB = add_mult_matrices(A, B,'multiply')

print('AB:', '\n', AB)

AB: 
 [[-2  2]
 [ 2 -2]]


In [96]:
options = {
    'a': np.array([[-2, 2], [2, -2]]),
    'b': np.array([[2, -2], [-2, 2]]),
    'c': np.array([[-2, 2], [-2, 2]]),
    'd': np.array([[-2, -2], [2, 2]])}

for key, value in options.items():
    if np.array_equal(AB, value):
        print(f"The correct answer is: {key})")

The correct answer is: a)


**Chap 6. Question 1**

In [112]:
matrix1 = np.array([[5, 6], [4, 5]])
matrix2 = np.array([[6, 4], [3, 3]])

In [115]:
matrix1_inv = np.linalg.inv(matrix1)
matrix2_inv = np.linalg.inv(matrix2)

print('Inverse of Matrix 1:', '\n', matrix1_inv)
print()
print('Inverse of Matrix 2:', '\n', matrix2_inv)

Inverse of Matrix 1: 
 [[ 5. -6.]
 [-4.  5.]]

Inverse of Matrix 2: 
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [124]:
matrix = np.array([[2, 2], [1, 2]])
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)

[[ 1.  -1. ]
 [-0.5  1. ]]


In [125]:
options = {
    'a': np.array([[1, -1], [-0.5, 1]]),
    'b': np.array([[-1, 1], [0.5, -1]]),
    'c': np.array([[1, 1], [-0.5, -1]]),
    'd': np.array([[-1, -1], [0.5, 1]])}

for key, value in options.items():
    if np.array_equal(matrix_inv, value):
        print(f"The correct answer is option: ({key})")

The correct answer is option: (a)


**Chap10. Question 1 a)**

In [133]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])

x = np.linalg.solve(A, b)

print(x)

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [132]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

x = np.linalg.solve(A, b)

print(x)

[ 8.  2. -1.]


**Chap 12. Question 1**

In [138]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

In [139]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

To check whether v1 and v2 are views or copies, we can use the base attribute of NumPy arrays. If an array is a view, its base attribute will point to the original array. If it's a copy, its base attribute will be None.

v1 is an original array, and v2 is a view of the last two elements of v1. 
When using its base attribute v2 is pointing to the original array v1.

If we change the last element in v2 to 123, the last element in v1 be changed aswell since v2 is a view, meaning they share the same data buffer.
If v2 were a copy, changes made to v2 would not affect v1 at all.

In [141]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [142]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [143]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
